name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [Linux, Windows, HTML5]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: downfall
          preset: ${{ matrix.platform }}
          debugMode: "true"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}

      - name: Set up Netlify deploy
        if: ${{ matrix.platform == 'HTML5' }}
        run: |
          cp -rv ${{ github.workspace }}/${{ steps.build.outputs.build }} \
                 /home/runner/work/_temp/_github_home/build;
          mv /home/runner/work/_temp/_github_home/build/downfall \
             /home/runner/work/_temp/_github_home/build/index.html;

      - name: Deploy to Netlify
        uses: danakim/gh-action-deploy-netlify@master
        if: ${{ matrix.platform == 'HTML5' }}
        with:
          AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOY_PROD: false
